apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-sns-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-sns-jib
  template:
    metadata:
      labels:
        app: aws-sns-jib
    spec:
      containers:
        - name: aws-sns-jib-pod
          image: vsaad/aws:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aws-sns-jib-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
  selector:
    app: aws-sns-jib
    